name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.100

    - name: Build & test
      run: dotnet test --configuration Release --logger GitHubActions

    - name: Build & publish
      run: dotnet publish OsuHelper/ -o OsuHelper/bin/Publish/ -c Release -r win-x86 --self-contained false

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: OsuHelper
        path: OsuHelper/bin/Publish/
